@EmployeesAPI_HostAddress = https://localhost:7065

GET {{EmployeesAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

@id=string
DELETE {{EmployeesAPI_HostAddress}}/api/employees/string

###

GET {{EmployeesAPI_HostAddress}}/api/employees

###
